language: node_js
cache:
  directories:
      - ~!@/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
  # - echo 'url-personalizada.com' > public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: development